spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: ${OPENAI_CHAT_MODEL}
        temperature: ${OPENAI_CHAT_TEMPERATURE}
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false

server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  forward-headers-strategy: ${SERVER_FORWARD_HEADERS_STRATEGY:framework}

jwt:
  secret: ${JWT_SECRET_KEY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_S3_REGION}

services:
  analyze:
    url: ${SERVICES_ANALYZE_URL}

logging:
  level:
    root: INFO
    com.likelionknu.notdesign: INFO
